import { NextRequest, NextResponse } from "next/server";
import { getSupabaseClient } from "@/lib/api-supabase";
import { generateRoute } from "@/lib/route-generator";

const FREE_ROUTE_LIMIT = 5;
const RATE_LIMIT_SECONDS = 30;
const MAX_BODY_SIZE = 512_000; // 512 KB (pre-generated routes include geometry)

export async function POST(request: NextRequest) {
  try {
    // Validate body size
    const contentLength = request.headers.get("content-length");
    if (contentLength && parseInt(contentLength, 10) > MAX_BODY_SIZE) {
      return NextResponse.json(
        { error: "Corps de requête trop volumineux" },
        { status: 413 }
      );
    }

    const { supabase } = await getSupabaseClient(request);

    // Check auth
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: "Non authentifié" }, { status: 401 });
    }

    // Rate limiting: check last route created_at
    const { data: lastRoute } = await supabase
      .from("routes")
      .select("created_at")
      .eq("user_id", user.id)
      .order("created_at", { ascending: false })
      .limit(1)
      .single();

    if (lastRoute?.created_at) {
      const lastCreated = new Date(lastRoute.created_at).getTime();
      const now = Date.now();
      const secondsSinceLast = (now - lastCreated) / 1000;

      if (secondsSinceLast < RATE_LIMIT_SECONDS) {
        const retryAfter = Math.ceil(RATE_LIMIT_SECONDS - secondsSinceLast);
        return NextResponse.json(
          {
            error: "rate_limited",
            message: `Veuillez attendre ${retryAfter}s avant de générer un nouveau parcours.`,
            retry_after: retryAfter,
          },
          {
            status: 429,
            headers: { "Retry-After": String(retryAfter) },
          }
        );
      }
    }

    // Check quota
    const { count, error: countError } = await supabase
      .from("routes")
      .select("*", { count: "exact", head: true })
      .eq("user_id", user.id);

    if (countError) {
      console.error("Count error:", countError);
      return NextResponse.json(
        { error: "Erreur lors de la vérification du quota" },
        { status: 500 }
      );
    }

    const routeCount = count ?? 0;

    if (routeCount >= FREE_ROUTE_LIMIT) {
      return NextResponse.json(
        {
          error: "limit_reached",
          message: "Vous avez atteint la limite de 5 parcours gratuits.",
          count: routeCount,
          limit: FREE_ROUTE_LIMIT,
        },
        { status: 403 }
      );
    }

    // Parse and validate body
    const rawBody = await request.text();
    if (rawBody.length > MAX_BODY_SIZE) {
      return NextResponse.json(
        { error: "Corps de requête trop volumineux" },
        { status: 413 }
      );
    }

    let body: unknown;
    try {
      body = JSON.parse(rawBody);
    } catch {
      return NextResponse.json(
        { error: "JSON invalide" },
        { status: 400 }
      );
    }

    if (typeof body !== "object" || body === null || Array.isArray(body)) {
      return NextResponse.json(
        { error: "Le body doit être un objet JSON" },
        { status: 400 }
      );
    }

    const { lat, lng, targetSteps } = body as Record<string, unknown>;

    if (typeof lat !== "number" || typeof lng !== "number" || isNaN(lat) || isNaN(lng)) {
      return NextResponse.json(
        { error: "lat et lng sont requis (nombres)" },
        { status: 400 }
      );
    }

    if (lat < -90 || lat > 90 || lng < -180 || lng > 180) {
      return NextResponse.json(
        { error: "Coordonnées invalides" },
        { status: 400 }
      );
    }

    const steps = typeof targetSteps === "number" && targetSteps >= 2000 && targetSteps <= 15000
      ? Math.round(targetSteps / 1000) * 1000
      : 10000;

    // Check if route was pre-generated by native client
    const { preGenerated } = body as Record<string, unknown>;

    let routeDistance: number;
    let routeSteps: number;
    let routeGeometry: unknown;
    let routeDuration: number;
    let routeManeuvers: unknown[] = [];

    if (
      preGenerated &&
      typeof preGenerated === "object" &&
      !Array.isArray(preGenerated)
    ) {
      // Native client generated the route locally — just validate and save
      const pg = preGenerated as Record<string, unknown>;
      if (
        typeof pg.distance_m !== "number" || pg.distance_m < 0 ||
        typeof pg.steps_estimate !== "number" || pg.steps_estimate < 0 ||
        typeof pg.duration_s !== "number" || pg.duration_s < 0 ||
        typeof pg.geometry !== "object" || pg.geometry === null ||
        (pg.geometry as Record<string, unknown>).type !== "LineString"
      ) {
        return NextResponse.json(
          { error: "Données de parcours pré-généré invalides" },
          { status: 400 }
        );
      }
      routeDistance = Math.round(pg.distance_m as number);
      routeSteps = Math.round(pg.steps_estimate as number);
      routeDuration = Math.round(pg.duration_s as number);
      routeGeometry = pg.geometry;
      routeManeuvers = Array.isArray(pg.maneuvers) ? pg.maneuvers : [];
    } else {
      // Server-side generation (web client)
      const route = await generateRoute(lat, lng, steps);
      routeDistance = route.distance;
      routeSteps = route.stepsEstimate;
      routeDuration = route.duration;
      routeGeometry = route.geometry;
      routeManeuvers = route.maneuvers;
    }

    // Save to DB
    const { data: insertedRoute, error: insertError } = await supabase
      .from("routes")
      .insert({
        user_id: user.id,
        start_lat: lat,
        start_lng: lng,
        distance_m: routeDistance,
        steps_estimate: routeSteps,
        geometry: routeGeometry,
        duration_s: routeDuration,
        status: "generated",
      })
      .select("id")
      .single();

    if (insertError) {
      console.error("Insert error:", insertError);
      return NextResponse.json(
        { error: "Erreur lors de la sauvegarde du parcours" },
        { status: 500 }
      );
    }

    return NextResponse.json({
      id: insertedRoute?.id ?? null,
      distance_m: routeDistance,
      duration_s: routeDuration,
      steps_estimate: routeSteps,
      geometry: routeGeometry,
      maneuvers: routeManeuvers,
      routes_used: routeCount + 1,
      routes_limit: FREE_ROUTE_LIMIT,
    });
  } catch (error) {
    console.error("Route generation error:", error);
    return NextResponse.json(
      { error: "Erreur lors de la génération du parcours" },
      { status: 500 }
    );
  }
}
